language: android
android:
  components:
    - tools
    - platform-tools
    - tools

    - build-tools-27.0.2
    - android-27
    - extra-android-support
    - extra-android-m2repository

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - cp ./google-licenses/* "$ANDROID_HOME/licenses/"

script:
- ./gradlew clean assemble
